### ISSUE TITLE
Modalcontent is loaded/parsed when modal is hidden (iframes)

### ISSUE THREAD

**Issue by Michael-Hamburger** [thephuse/vanilla-modal#15]
Hello!

I am using vanilla-modal to show modals without the need of jquery or bootstrap. That's cool.
The content of the modal is an iframe. The iframe src is a file on my server. When I close the modal I can see that the file on the server is loaded and the chrome developer tools shows me that the file is parsed.

This is unnecessary and in my case bad because I use the modal to show the user payment options (paypal, stripe, ...). The api of these companies are queried and the pay/checkout buttons are created although the modal is closed.

If you want to check the behaviour just add **onload="alert('load')"** on the modal-3 iframe to your example http://thephuse.github.io/vanilla-modal/ and open it. Wait till it loaded, click the alert, close it, wait, alert is shown (because it loads again).

~~Do you have any idea why this is the case?~~

*edit*
looks like _releaseNode() is the culprit. The childNodes of the modalContent is copied back to he current-obj. This also mean that the iframe src is loaded again. As possible workaround the _releaseNode() checks if the child is an iframe and doesn't copy it (the iframe src will be loaded when rendered). Any other ideas?

**Comment by benceg** [comment]
@Michael-Hamburger quite right there. Nodes are taken directly from the DOM and released back to their original position to retain any JS event listeners (or otherwise) attached to those nodes and their children. This is fully intentional behaviour.

One workaround would be to use the `onBeforeOpen` hook to add the `src` attribute to the iframe ahead of opening it, and an `onBeforeClose` hook to remove it. Your code might look something like this:

```js
const iframe = document.getElementById('my-iframe');
const iframeSrc = iframe.src;

iframe.removeAttribute('src');

const modal = new VanillaModal({
  onBeforeOpen: function() {
    iframe.src = iframeSrc;
  },
  onBeforeClose: function() {
    iframe.removeAttribute('src');
  }
});
```

If it's an issue that the iframe is loaded into the DOM in the first place, you can have an empty modal container on the page and create an iframe dynamically on onBeforeOpen, appending it to the iframe container and removing it using onBeforeClose. And if it's a worry that the iframe _can_ be loaded multiple times by opening & closing the modal, it might just make more sense not to use an iframe, but rather to have those payment options loaded directly into the DOM of the page concerned.
