### ISSUE TITLE
Open dinamically modal inside modal

### ISSUE THREAD

**Issue by leeeandroo** [thephuse/vanilla-modal#16]
Hello,

I'm using the vanilla-modal inside a angular2 project. 

When I use the rel attribute, like:

`<a href="#modalLogin" title="Login" rel="modal:open">Login</a>`

and inside this modalLogin, I call another modal using the same way:

`<a href="#modalSignup" title="Signup" rel="modal:open">Signup</a>`

But, I'm trying to create a directive to make this auto to open. So, on the click I call a method that does this:

`<a href="#" title="Signup" modelopener="modalSignup">Signup</a>`

```
const modal = new VanillaModal({
      open: this.modalToOpen
});

modal.open('#'+this.modalToOpen);
```

The modal insert the content in the same modal as opened and when I close and open the second modal, the content is blank because It's inserted on the first. 
I try to use destroy or force to close before open the new one with no success.

Do I'm making a mistake? Is it possible to do on this way?

**Comment by smoruetasantiago** [comment]
Maybe it's not your case, if you are using styles from demo, you could try to delete them. I had the same problem than you and now it's ok

**Comment by leeeandroo** [comment]
Unfortunately It's not my case. I'm not using the styles from demo. 

I think I'm making a mistake with js instance, but I don't know how I can resolve this.

**Comment by benceg** [comment]
Hi @leeeandroo,

In order to open a second modal with a fresh set of parameters inside an existing modal, you'll need to instantiate VanillaModal twice.

A new instance of VanillaModal needs to exist for every modal you would like to have open at any one time on the page. In other words, if you'd like to overlay three modals above each other, you'll need to have three VanillaModal instances.

I'm not sure how that will tie in with your Angular 2 component... good luck!
