### ISSUE TITLE
Array.from not supported on IE

### ISSUE THREAD

**Issue by aplana-pbx** [thephuse/vanilla-modal#23]
[This usage](https://github.com/thephuse/vanilla-modal/blob/master/dist/index.js#L66) of Array.from is causing errors on IE, as it's currently [not supported](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Browser_compatibility).

(Sorry for not providing a PR!)

**Comment by makedonec88** [comment]
yep, the same. Not working even in plugin demo page.
However, working with polyfill from [mozilla devellopers page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).

**Comment by AnalogMemory** [comment]
@makedonec88 how do you get a polyfill to work with this library? I loaded one before requiring the modal.

**Comment by besimhu** [comment]
@AnalogMemory you can just load the mozilla polyfill right before the source code. Additionally you could load the polyfills before loading the library.

**Comment by benceg** [comment]
Hi folks, and sorry about that.

You may be pleased to know that I've fixed this regression, which was due to an assumption in Babel 6's compiler that it'd be targeting an environment that supports `Array.prototype.from` or has an equivalent polyfill. Just hit `npm i -S vanilla-modal` if using NPM, to update the script.
