### ISSUE TITLE
Issues with TurboLinks 5 

### ISSUE THREAD

**Issue by panoply** [thephuse/vanilla-modal#24]
Having issues re-initialising when using in conjunction with TurboLinks / Ajax requests. Vanilla target modal fails to be found. Any workaround in dealing with this?

**Update:**

For those running into issues, the best option to take is to `destory()` on a turbolinks render event.
This solution seems hacky:

```
document.addEventListener("turbolinks:render", function() {
      vanillaModal.destroy();
}); 
```

**Update 2**

After some troubleshooting the issue would arise when initialising vanilla-modal via href anchor attribute, e.g:  ` <a href="#modal" data-modal-open>Open Modal</a>`  Turbolinks is interpreting the anchor as a request and not importing the cloned element vanilla-modal injects to the `modal-content` element. Anyway, instead of calling `turbolinks:render` initialise using JavaScript. Seriously, don't try and be a fucking hero **just init with JS**:

HTML
`<button type="button" class="modal-button">Open Modal</button>`

JavaScript
```
var vanillaModal = new VanillaModal.default();

var hamburger = document.getElementsByClassName('open-modal')[0]; 
hamburger.addEventListener("click", function(){
     return vanillaModal.open('#modal');
}) 
```

**Comment by wkirby** [comment]
I'm getting whacky behavior with Turbolinks, too, and calling `destroy` on `turbolinks` events and opening modals with javascript aren't actually solving the problem.

A little debugging, and in my case the problem is the code initializing my modal is being run on every page request, leading to several instances of `VanillaModal` on the page, all competing, and generally wreaking havoc.
