### ISSUE TITLE
Semver and compatible version issue

### ISSUE THREAD

**Issue by frankcs** [thephuse/vanilla-modal#28]
Hi great work with this package, it suits almost perfectly my project needs. One minor caveat:

"dependencies": {
    "vanilla-modal": "^1.3.0"
  }

I have this in my package.json for your vanilla-modal. Watching your releases by version 1.5.1 you make the breaking change. I have made a fresh npm install and got your dependency with all the breaking changes, that I can't deal with right now. The solution for me will be to point directly to the 1.3.0 version and not to a "compatible" version.

 According to:
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
You should have bumped your major version number because everyone using that syntax will not get a `compatible` version, thus breaking their project. 

I'll try to update to the newer version ASAP, but i think it would be nice that semver would work as expected on this magnific package :)

**Comment by benceg** [comment]
Hi @frankcs, and thank you for your great comments!

I was debating whether to bump to a major, but ultimately decided against it due to the fact that there are no breaking changes to the methods and calls within the API. There _are_, however, changes to the default settings with which the modal is instantiated.

Say you currently have something like:

```js
const modal = new VanillaModal();
```

You'll need to update that to:

```js
const modal = new VanillaModal({
  open: '[rel="modal:open"]',
  close: '[rel="modal-close"]'
});
```

That should be the only step you need to take to get everything working with v1.5+.

Please let me know if this solves your problem!
